Blinking & UI Bars
SCP-Godot/SCPCB pull request #3
Opened 2022-12-07 09:20 UTC by rezbyte

[bars.webm](https://user-images.githubusercontent.com/48037381/206138572-db9dab63-6e63-4ec6-aa4a-7216144bfcca.webm)

I've implemented blinking for the player & got the bars on the HUD working:
- Added a generic bar component
- Derived the stamina & blink bars from bar component
- Added a blink animation to the player
- Implemented a blink timer into the player

I didn't know whether you'd prefer these as two separate PRs (that depend on each other) or just one.

2022-12-12 15:06 UTC, dnesov requested changes
Good job on this PR! However, as I pointed out in Player.gd's comments, we should not have references/logic to UI in this class. I suggest creating a child of Player called "PlayerGUI" or similar that would connect to Player's signals and change the UI whenever Player calls these signals. In the future however, we want to refactor the player script entirely.

2022-12-12 15:06 UTC, dnesov commented on Scripts/Player.gd
> +@onready var blink_overlay: ColorRect = $UI/Blink
Player class shouldn't be responsible for UI. Ideally, create a separate node that listens for player's signals and changes it's child controls accordingly.

2022-12-13 04:29 UTC, rezbyte commented
> Good job on this PR! However, as I pointed out in Player.gd's comments, we should not have references/logic to UI in this class. I suggest creating a child of Player called "PlayerGUI" or similar that would connect to Player's signals and change the UI whenever Player calls these signals. In the future however, we want to refactor the player script entirely.

Thanks for the code review! :slightly_smiling_face: 
I've added signals for opening & closing the player's eyes.
As well as signals for changes to stamina & the blink timer.
All of which is handled by a new script attached to the `UI` node in the player.

2022-12-13 13:25 UTC, dnesov commented
Much better, thank you for your changes! I'll merge the PR now.

2022-12-13 13:25 UTC, merged